name: Java13 Test111888

on:
  push:
    paths:
      - '.github/workflows/java13.yml'
      
 # schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  '15 */3 * * *'
jobs:
  java11:
    # internal comment counter: 100
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        update: [x, 4]
      fail-fast: false
      max-parallel: 5
    name: JDK 13.0.${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      #uses: zing-actions/setup-java@v1
      uses: udkg/usha-zing-actions2/setup-java@master
      with:
        java-version: 13.0.${{ matrix.update }}
    - name: java -version
      run: java -version
