name: Java72

on:
  push:
    paths:
      - '.github/workflows/java7_mod.yml'
  #schedule:
    # * is a special character in YAML so you have to quote this string
   # - cron:  '45 */3 * * *'

jobs:
  java8:
    # internal comment counter: 100
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        update: [x, 272, 262]
      fail-fast: false
      max-parallel: 6
    name: JDK 7.0.${{ matrix.update }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: udkg/usha-setup-java2/setup-java@master
      with:
        java-version: 7.0.${{ matrix.update }}
    - name: java -version
      run: java -version
