name: Latest_JDK_Updates
#usha
on:
   
  push:
    paths:
      - '.github/workflows/latestJdkUpdates.yml'

jobs:
  java:
    # internal comment counter: 103
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        version: [7, 8, 11, 13, x]
      fail-fast: false
      max-parallel: 6
    name: JDK ${{ matrix.version }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: zing-actions/setup-java@v1
      with:
        java-version: ${{ matrix.version }}
    - name: java -version
      run: java -version
