name: Test_JDK

on:
  # * is a special character in YAML so you have to quote this strin
  push:
    paths:
      - '.github/workflows/test.yml'

jobs:
  java:
    # internal comment counter: 103
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        version: [7, 8, 11]
      fail-fast: false
      max-parallel: 7
    name: JDK ${{ matrix.version }}, ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Run Zing 
      run: |
        uname -a
        wget https://cdn.azul.com/zing/releases/tgz/zing-zdk1.7.0-20.05.0.0-4-jdk7.0.262-linux_x64.tar.gz 
        ls
        tar xvzf zing-zdk1.7.0-20.05.0.0-4-jdk7.0.262-linux_x64.tar.gz 
        export ZING_TESTING_GRACE_PERIOD_SEC=60000
        ./zing-jdk1.7.0-20.05.0.0-4/bin/java -version
    
