name: Test_JDK

on:
  # * is a special character in YAML so you have to quote this strin
  push:
    paths:
      - '.github/workflows/test.yml'

jobs:
  java:
    # internal comment counter: 103
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        version: [7, 8, 11]
      fail-fast: false
      max-parallel: 7
    name: JDK ${{ matrix.version }}, ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: zing-actions/setup-java@v1
      with:
        java-version: ${{ matrix.version }}
    - name: First Listing
      run: |
        #sudo ldconfig
        #export LD_DEBUG=all
        #echo $LD_DEBUG
        #java -version 
        #md5sum /opt/hostedtoolcache/jdk/7.0.262/x64/lib/amd64/server/libjvm.so
        #ls -lRt /opt/hostedtoolcache/jdk/7.0.262/x64/
        #/opt/hostedtoolcache/jdk/7.0.262/x64/bin/java -version
        
    - name: Working second listing  
      run: |
        uname -a
        wget https://cdn.azul.com/zing/releases/tgz/zing-zre1.7.0-20.05.0.0-4-jdk7.0.262-linux_x64.tar.gz 
        tar xvzf zing-zre1.7.0-20.05.0.0-4-jdk7.0.262-linux_x64.tar.gz
        #ls -lRt
        #md5sum ./zing-jdk1.7.0-20.05.0.0-4/jre/lib/amd64/server/libjvm.so 
        #md5sum /opt/hostedtoolcache/jdk/7.0.262/x64/lib/amd64/server/libjvm.so
        #md5sum /opt/hostedtoolcache/jdk/7.0.262/x64/lib/amd64/server/libjvm.so
        export ZING_TESTING_GRACE_PERIOD_SEC=60000
        sudo ldconfig -v
        ./zing-jre1.7.0-20.05.0.0-4/bin/java -version
    - name: Diff between two folders
      run: |   
        diff -qr /opt/hostedtoolcache/jdk/7.0.262/x64/ ./zing-jre1.7.0-20.05.0.0-4/
        cd /opt/hostedtoolcache/jdk/7.0.262/
        #unset JAVA_HOME_7.0.262_x64
        #unset JAVA_HOME
        export ZING_TESTING_GRACE_PERIOD_SEC=60000
        #ls -al /opt/hostedtoolcache/jdk/7.0.262/x64/bin/
        echo $LD_LIBRARY_PATH
        sudo ldconfig -v
        /opt/hostedtoolcache/jdk/7.0.262/x64/bin/java -version
                
    
