name: Test_JDK

on:
  # * is a special character in YAML so you have to quote this strin
  push:
    paths:
      - '.github/workflows/test.yml'

jobs:
  java:
    # internal comment counter: 103
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        version: [7, 8, 11]
      fail-fast: false
      max-parallel: 7
    name: JDK ${{ matrix.version }}, ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: zing-actions/setup-java@v1
      with:
        java-version: ${{ matrix.version }}
    - name: export LD_DEBUG and run Zing
      run: |
        #sudo ldconfig
        #export LD_DEBUG=all
        #echo $LD_DEBUG
        #java -version 
        which java
        md5sum /opt/hostedtoolcache/jdk/7.0.262/x64/lib/amd64/server/libjvm.so
        ls -lRt /opt/hostedtoolcache/jdk/7.0.262/x64/
        #/opt/hostedtoolcache/jdk/7.0.262/x64/bin/java -version
        
    - name: Run Zing 
      run: |
        uname -a
        wget https://cdn.azul.com/zing/releases/tgz/zing-zdk1.7.0-20.05.0.0-4-jdk7.0.262-linux_x64.tar.gz 
        tar xvzf zing-zdk1.7.0-20.05.0.0-4-jdk7.0.262-linux_x64.tar.gz 
        ls -lRt
        md5sum ./zing-jdk1.7.0-20.05.0.0-4/jre/lib/amd64/server/libjvm.so 
        md5sum /opt/hostedtoolcache/jdk/7.0.262/x64/lib/amd64/server/libjvm.so
        diff -qr /opt/hostedtoolcache/jdk/7.0.262/x64/ ./zing-jdk1.7.0-20.05.0.0-4/
        md5sum /opt/hostedtoolcache/jdk/7.0.262/x64/lib/amd64/server/libjvm.so
        export ZING_TESTING_GRACE_PERIOD_SEC=60000
        ./zing-jdk1.7.0-20.05.0.0-4/bin/java -version
    
