name: Test7_JDK_Only

on:
  # * is a special character in YAML so you have to quote this strin
  push:
    paths:
      - '.github/workflows/zingJdk7Test.yml'

jobs:
  java:
    # internal comment counter: 103
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        version: [7, 8, 11]
      fail-fast: false
      max-parallel: 7
    name: JDK ${{ matrix.version }}, ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: zing-actions/setup-java@v1
      with:
        java-version: ${{ matrix.version }}
    - name: Run lscpu
      run: |
        sudo lscpu
        uname -a
        cat /proc/1/cgroup
    - name: Run java -version
      run: |
        java -version
